global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
  
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
  
  - job_name: 'grinserver-node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          environment: 'production'
          host: 'grinserver'
  
  - job_name: 'grinserver-cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          environment: 'production'
          host: 'grinserver'

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
        labels:
          environment: 'production'
