global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
  
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
  
  - job_name: 'grinserver-node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          environment: 'production'
          host: 'grinserver'
  
  - job_name: 'grinserver-cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          environment: 'production'
          host: 'grinserver'

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
        labels:
          environment: 'production'

  - job_name: 'mongodb'
    static_configs:
      - targets: ['158.69.192.72:9216']
        labels:
          environment: 'demo'
          database: 'mongodb'
  
  - job_name: 'postgres'
    static_configs:
      - targets: ['158.69.192.72:9187']
        labels:
          environment: 'demo'
          database: 'postgres'
  
  - job_name: 'mysql'
    static_configs:
      - targets: ['158.69.192.72:9104']
        labels:
          environment: 'demo'
          database: 'mysql'
  
  - job_name: 'redis'
    static_configs:
      - targets: ['158.69.192.72:9121']
        labels:
          environment: 'demo'
          database: 'redis'
